 5 are now primary. All three behaviors are considered abuse of the net, and
are almost universally grounds for termination of the originator's email
account or network connection. In these senses the term `spam' has gone
mainstream, though without its original sense or folkloric freight - there is
apparently a widespread myth among {luser}s that "spamming" is what happens
when you dump cans of Spam into a revolving fan. Hormel, the makers of Spam,
have published a surprisingly enlightened position statement
(http://www.spam.com/ci/ci_in.htm) on the Internet usage. :spam bait: n.
Email addresses included in, or comprising the entirety of, a usenet message
so that spammers mining a newsgroup with an {address harvester} will collect
them. These addresses can be people who have offended or annoyed the poster,
or who are included so that a spammer will spam an official, thereby causing
himself trouble. One particularly effective form of spam bait is the address
of a {teergrube}. :spamblock: /spam'blok/ n. [poss. by analogy to sunblock]
Text inserted in an email address to render it invalid and thus useless to
spammers. For example, the address `jrandom@hacker.org' might be transformed
to `jrandom@NOSPAM.hacker.org'. Adding spamblock to an address is often
referred to as `munging' it (see {munge})-. This evasion tactic depends on
the fact that most spammers collect names with some sort of {address
harvester} on volumes too high to de-mung by hand, but individual humans
reading an email message can readily spot and remove a spamblock in the from
address. Note: This is not actually a very effective tactic, and may already
be passing out of use in early 1999 after about two years of life. In both
mail and news, it's essentially impossible to keep a smart address harvester
from mining out the addresses in the message header and trace lines.
Therefore the only people who can be protected are third parties mentioned by
email address in the message - not a common enough case to interest spammers.
:spamhaus: spam'hows n. Pejorative term for an internet service provider that
permits or even encourages {spam} mailings from its systems. The plural is
`spamhausen'. There is a web page devoted to tracking spamhausen
(http://www.spamhaus.org). The most notorious of the spamhausen was Sanford
Wallace's Cyber Promotions Inc., shut down by a lawsuit on 16 October 1997.
The anniversary of the shutdown is celebrated on Usenet as Spam Freedom Day,
but lesser imitators of the Spamford still infest various murky corners of
the net. Since prosecution of spammers became routine under the junk-fax laws
and statues specifically targeting spam, spamhausen have declined in relative
importance; today, hit-and-run attacks by spammers using {relay rape} and
{throwaway account}s on reputable ISPs seem to account for most of the flow.
:spamvertize: v. To advertise using {spam}. Pejorative. :spangle: n. [UK] The
singular of {bells and whistles}. see also {spungle}. :spawn: n.,vi. 1.
[techspeak] In UNIX parlance, to create a child process from within a
process. Technically this is a `fork'; the term `spawn' is a bit more general
and is used for threads (lightweight processes) as well as traditional
heavyweight processes. 2. In gaming, meant to indicate where (`spawn-point')
and when a player comes to life (or `re-spawns') after being killed. Opposite
of {frag}. :special-case: vt. To write unique code to handle input to or
situations arising in a program that are somehow distinguished from normal
processing. This would be used for processing of mode switches or interrupt
characters in an interactive interface (as opposed, say, to text entry or
normal commands), or for processing of {hidden flag}s in the input of a batch
program or {filter}. :speedometer: n. A pattern of lights displayed on a
linear set of LEDs (today) or nixie tubes (yesterday, on ancient mainframes).
The pattern is shifted left every N times the operating system goes through
its {main loop}. A swiftly moving pattern indicates that the system is mostly
idle; the speedometer slows down as the system becomes overloaded. The
speedometer on Sun Microsystems hardware bounces back and forth like the eyes
on one of the Cylons from the wretched "Battlestar Galactica" TV series.
Historical note: One computer, the GE 600 (later Honeywell 6000) actually had
an _analog_ speedometer on the front panel, calibrated in instructions
executed per second. :spell: n. Syn. {incantation}. :spelling flame: n. //
[Usenet] A posting ostentatiously correcting a previous article's spelling as
a way of casting scorn on the point the article was trying to make, instead
of actually responding to that point (compare {dictionary flame}). Of course,
people who are more than usually slovenly spellers are prone to think _any_
correction is a spelling flame. It's an amusing comment on human nature that
spelling flames themselves often contain spelling errors. :spider: The
Web-walking part of a search engine that collects pages for indexing in the
search engine's database. Also called a {bot}. The best-known spider is
Scooter, the web-walker for the Alta Vista search engine. :spider food: n.
Keywords embedded (usually invisibly) into a web page to attract search
engines (spiders). The intended result of including spider food in one's web
page is to insure that the page appears high on the list of matching entries
to a search engine query. There are right and wrong ways to do this; the
right way is a discreet `meta keywords' tag, the wrong way is to embed many
repeats of a keyword in comments (and many search engines now detect and
ignore the latter). :spiffy: /spi'fee/ adj. 1. Said of programs having a
pretty, clever, or exceptionally well-designed interface. "Have you seen the
spiffy {X} version of {empire} yet?" 2. Said sarcastically of a program that
is perceived to have little more than a flashy interface going for it. Which
meaning should be drawn depends delicately on tone of voice and context. This
word was common mainstream slang during the 1940s, in a sense close to 1.
:spike: v. To defeat a selection mechanism by introducing a (sometimes
temporary) device that forces a specific result. The word is used in several
industries; telephone engineers refer to spiking a relay by inserting a pin
to hold the relay in either the closed or open state, and railroaders refer
to spiking a track switch so that it cannot be moved. In programming
environments it normally refers to a temporary change, usually for testing
purposes (as opposed to a permanent change, which would be called
{hardwired}). :spin: vi. Equivalent to {buzz}. More common among C and Unix
programmers. see the discussion of `spinlock' under {busy-wait}. :spl:
/S-P-L/ [abbrev, from Set Priority Level] The way traditional Unix kernels
implement mutual exclusion by running code at high interrupt levels. Used in
jargon to describe the act of tuning in or tuning out ordinary communication.
Classically, spl levels run from 1 to 7; "Fred's at spl 6 today" would mean
that he is very hard to interrupt. "Wait till I finish this; I'll spl down
then." see also {interrupts locked out}. :splash screen: n. [Mac users] Syn.
{banner}, sense 3. :splat: n. 1. Name used in many places (DEC, IBM, and
others) for the asterisk (`*') character (ASCII 0101010). This may derive
from the `squashed-bug' appearance of the asterisk on many early line
printers. 2. [MIT] Name used by some people for the `#' character (ASCII
0100011). 3. The {feature key} on a Mac (same as {alt}, sense 2). 4. obs.
Name used by some people for the Stanford/ITS extended ASCII circle-x
character. This character is also called `blobby' and `frob', among other
names; it is sometimes used by mathematicians as a notation for `tensor
product'. 5. obs. Name for the semi-mythical Stanford extended ASCII
circle-plus character. see also {{ASCII}}. :splat out: v. [Usenet; syn.
`disemvowel'] To partially obscure a potentially provocative word by
substituting {splat} characters for some of its letters (usually, but not
always, the vowels). The purpose is not to make the word unrecognizable but
to make it a mention rather than a use, so that no flamewar ensues. Words
often splatted out include N*z* (see {Godwin's Law}), k*bo* (see {KIBO, sense
2}), *v*l*t**n (anywhere fundamentalists might be lurking), *b*rt**n, and g*n
c*ntr*l. Compare {UN*X}. :spod: n. [UK] 1. A lower form of life found on
{talker system}s and {MUD}s. The spod has few friends in {RL} and uses
talkers instead, finding communication easier and preferable over the net. He
has all the negative traits of the {computer geek} without having any
interest in computers per se. Lacking any knowledge of or interest in how
networks work, and considering his access a God-given right, he is a major
irritant to sysadmins, clogging up lines in order to reach new MUDs,
following passed-on instructions on how to sneak his way onto Internet ("Wow!
It's in America!") and complaining when he is not allowed to use busy routes.
A true spod will start any conversation with "Are you male or female?" (and
follow it up with "Got any good numbers/IDs/passwords?") and will not talk to
someone physically present in the same terminal room until they log onto the
same machine that he is using and enter talk mode. Compare {newbie},
{tourist}, {weenie}, {twink}, {terminal junkie}, {warez d00dz}. 2. A
{backronym} for "Sole Purpose, Obtain a Degree"; according to some
self-described spods, this term is used by indifferent students to condemn
their harder-working fellows. Compare the defiant adoption of the term `geek'
in the mid-1990s by people who would previously have been stigmatized by it
(see {computer geek}). 3. [Glasgow University] An otherwise competent hacker
who spends way too much time on talker systems. 4. [obs.] An ordinary person;
a {random}. This is the meaning with which the term was coined, but the
inventor informs us he has himself accepted sense 1. :spoiler: n. [Usenet] 1.
A remark which reveals important plot elements from books or movies, thus
denying the reader (of the article) the proper suspense when reading the book
or watching the movie. 2. Any remark which telegraphs the solution of a
problem or puzzle, thus denying the reader the pleasure of working out the
correct answer (see also {interesting}). Either sense readily forms compounds
like `total spoiler', `quasi-spoiler' and even `pseudo-spoiler'. By
convention, articles which are spoilers in either sense should contain the
word `spoiler' in the Subject: line, or guarantee via various tricks that the
answer appears only after several screens-full of warning, or conceal the
sensitive information via {rot13}, {spoiler space} or some combination of
these techniques. :spoiler space: [also `spoiler spoo'] A screenful of blank
lines (and, often, form-feeds) deliberately inserted in a message following a
{spoiler} warning, so the actual spoiler can't be seen without hitting a key.
:sponge: n. [Unix] A special case of a {filter} that reads its entire input
before writing any output; the canonical example is a sort utility. Unlike
most filters, a sponge can conveniently overwrite the input file with the
output data stream. If a file system has versioning (as ITS did and VMS does
now) the sponge/filter distinction loses its usefulness, because directing
filter output would just write a new version. see also {slurp}. :spoof: vi.
To capture, alter, and retransmit a communication stream in a way that
misleads the recipient. As used by hackers, refers especially to altering
TCP/IP packet source addresses or other packet-header data in order to
masquerade as a trusted machine. This term has become very widespread and is
borderline techspeak. :spool: vi. [from early IBM `Simultaneous Peripheral
Operation On-Line', but is widely thought to be a {backronym}] To send files
to some device or program (a `spooler') that queues them up and does
something useful with them later. Without qualification, the spooler is the
`print spooler' controlling output of jobs to a printer; but the term has
been used in connection with other peripherals (especially plotters and
graphics devices) and occasionally even for input devices. see also {demon}.
:spool file: n. Any file to which data is {spool}ed to await the next stage
of processing. Especially used in circumstances where spooling the data copes
with a mismatch between speeds in two devices or pieces of software. For
example, when you send mail under Unix, it's typically copied to a spool file
to await a transport {demon}'s attentions. This is borderline techspeak.
:spungle: n. [Durham, UK; portmanteau, {spangle} + bungle] A {spangle} of no
actual usefulness. Example: Roger the Bent Paperclip in Microsoft Word '98. A
spungle's only virtue is that it looks pretty, unless you find creeping
featurism ugly. :square tape: n. Mainframe magnetic tape cartridges for use
with IBM 3480 or compatible tape drives; or QIC tapes used on workstations
and micros. The term comes from the square (actually rectangular) shape of
the cartridges; contrast {round tape}. :squirrelcide: n. [common on Usenet's
comp.risks newsgroup.] (alt. `squirrelicide') What all too frequently happens
when a squirrel decides to exercise its species's unfortunate penchant for
shorting out power lines with their little furry bodies. Result: one dead
squirrel, one down computer installation. In this situation, the computer
system is said to have been squirrelcided. :stack: n. The set of things a
person has to do in the future. One speaks of the next project to be attacked
as having risen to the top of the stack. "I'm afraid I've got real work to
do, so this'll have to be pushed way down on my stack." "I haven't done it
yet because every time I pop my stack something new gets pushed." If you are
interrupted several times in the middle of a conversation, "My stack
overflowed" means "I forget what we were talking about." The implication is
that more items were pushed onto the stack than could be remembered, so the
least recent items were lost. The usual physical example of a stack is to be
found in a cafeteria: a pile of plates or trays sitting on a spring in a
well, so that when you put one on the top they all sink down, and when you
take one off the top the rest spring up a bit. see also {push} and {pop}. At
MIT, {PDL} used to be a more common synonym for {stack} in all these
contexts, and this may still be true. Everywhere else {stack} seems to be the
preferred term. {Knuth} ("The Art of Computer Programming", second edition,
vol. 1, p. 236) says: Many people who realized the importance of stacks and
queues independently have given other names to these structures: stacks have
been called push-down lists, reversion storages, cellars, nesting stores,
piles, last-in-first-out ("LIFO") lists, and even yo-yo lists! :stack puke:
n. Some processor architectures are said to `puke their guts onto the stack'
to save their internal state during exception processing. The Motorola 68020,
for example, regurgitates up to 92 bytes on a bus fault. On a pipelined
machine, this can take a while. :stale pointer bug: n. Synonym for {aliasing
bug} used esp. among microcomputer hackers. :star out: v. [University of
York, England] To replace a user's encrypted password in /etc/passwd with a
single asterisk. Under Unix this is not a legal encryption of any password;
hence the user is not permitted to log in. In general, accounts like adm,
news, and daemon are permanently "starred out"; occasionally a real user
might have the this inflicted upon him/her as a punishment, e.g. "Graham was
starred out for playing Omega in working hours". Also occasionally known as
The Order Of The Gold Star in this context. "Don't do that, or you'll be
awarded the Order of the Gold Star..." Compare {disusered}. :state: n. 1.
Condition, situation. "What's the state of your latest hack?" "It's winning
away." "The system tried to read and write the disk simultaneously and got
into a totally {wedged} state." The standard question "What's your state?"
means "What are you doing?" or "What are you about to do?" Typical answers
are "about to gronk out", or "hungry". Another standard question is "What's
the state of the world?", meaning "What's new?" or "What's going on?". The
more terse and humorous way of asking these questions would be "State-p?".
Another way of phrasing the first question under sense 1 would be "state-p
latest hack?". 2. Information being maintained in non-permanent memory
(electronic or human). :stealth manager: n. [Corporate DP] A manager that
appears out of nowhere, promises undeliverable software to unknown end users,
and vanishes before the programming staff realizes what has happened. see
{smoke and mirrors}. :steam-powered: adj. Old-fashioned or underpowered;
archaic. This term does not have a strong negative loading and may even be
used semi-affectionately for something that clanks and wheezes a lot but
hangs in there doing the job. :steved: adj.,v. /steevd/ [Apple employees and
users] Terminated, said of a development project. Originated after Steven P.
Jobs returned to Apple as acting CEO in 1997. Jobs immediated axed several
development projects, including OpenDoc and Newton that had been launched by
John Sculley, the man who had ousted Jobs in the mid 1980s. Now any project
shut down at Apple and often at any large firm connected with Apple may be
said to have gotten steved. It is usually spelled lowercase despite the
origin. It is almost always past-tense and used quasi-adjectivally. :STFW:
imp. /S-T-F-W/ [Usenet] Commmon abbreviation for "Search The Fucking Web", a
suggestion that what you're asking for is a query better handled by a search
engine than a human being. Usage is common and exactly parallel to both
senses of {RTFM}. :stiffy: n. 3.5-inch {microfloppies}, so called because
their jackets are more rigid than those of the 5.25-inch and the (now totally
obsolete) 8-inch floppy. Elsewhere this might be called a `firmy'. For some
odd reason, several sources have taken the trouble to inform us that this
term is widespread in South Africa. :stir-fried random: n. (alt. `stir-fried
mumble') Term used for the best dish of many of those hackers who can cook.
Consists of random fresh veggies and meat wokked with random spices. Tasty
and economical. see {random}, {great-wall}, {ravs}, {{laser chicken}},
{{oriental food}}; see also {mumble}. :stomp on: vt. To inadvertently
overwrite something important, usually automatically. "All the work I did
this weekend got stomped on last night by the nightly server script." Compare
{scribble}, {mangle}, {trash}, {scrog}, {roach}. :Stone Age: n.,adj. 1. In
computer folklore, an ill-defined period from ENIAC (ca. 1943) to the
mid-1950s; the great age of electromechanical {dinosaur}s. Sometimes used for
the entire period up to 1960-61 (see {Iron Age}); however, it is funnier and
more descriptive to characterize the latter period in terms of a `Bronze Age'
era of transistor-logic, pre-ferrite-{core} machines with drum or CRT mass
storage (as opposed to just mercury delay lines and/or relays). see also
{Iron Age}. 2. More generally, a pejorative for any crufty, ancient piece of
hardware or software technology. Note that this is used even by people who
were there for the {Stone Age} (sense 1). :stone knives and bearskins: n.
[from the Star Trek Classic episode "The City on the Edge of Forever"] A term
traditionally used to describe (and deprecate) computing environments that
are grotesquely primitive in light of what is known about good ways to design
things. As in "Don't get too used to the facilities here. Once you leave SAIL
it's stone knives and bearskins as far as the eye can see". Compare
{steam-powered}. :stoppage: /sto'p*j/ n. Extreme {lossage} that renders
something (usually something vital) completely unusable. "The recent system
stoppage was caused by a {fried} transformer." :store: n. [prob. from
techspeak `main store'] In some varieties of Commonwealth hackish, the
preferred synonym for {core}. Thus, `bringing a program into store' means not
that one is returning shrink-wrapped software but that a program is being
{swap}ped in. :strided: /stri:'d*d/ adj. [scientific computing] Said of a
sequence of memory reads and writes to addresses, each of which is separated
from the last by a constant interval called the `stride length'. These can be
a worst-case access pattern for the standard memory-caching schemes when the
stride length is a multiple of the cache line size. Strided references are
often generated by loops through an array, and (if your data is large enough
that access-time is significant) it can be worthwhile to tune for better
locality by inverting double loops or by partially unrolling the outer loop
of a loop nest. This usage is borderline techspeak; the related term `memory
stride' is definitely techspeak. :stroke: n. Common name for the slant (`/',
ASCII 0101111) character. see {ASCII} for other synonyms. :strudel: n. Common
(spoken) name for the at-sign (`@', ASCII