 :SAIL:: /sayl/, not /S-A-I-L/ n. 1. The Stanford Artificial Intelligence
Lab. An important site in the early development of LISP; with the MIT AI Lab,
BBN, CMU, XEROX PARC, and the UNIX community, one of the major wellsprings of
technical innovation and hacker-culture traditions (see the {{WAITS}} entry
for details). The SAIL machines were shut down in late May 1990, scant weeks
after the MIT AI Lab's ITS cluster was officially decommissioned. 2. The
Stanford Artificial Intelligence Language used at SAIL (sense 1). It was an
Algol-60 derivative with a coroutining facility and some new data types
intended for building search trees and association lists.